#167729793 Users should book a return Trip
andela/shadowcat-backend pull request #31
Opened 2019-09-03 07:15 UTC by davidfrank96

#### What does this PR do?
** A User will be able to book a return Trip 
#### Description of Task to be completed?
- created a return Trip controller
- Created a Trips table
- created a validation Handler for handling errors
- created a date validation function
- created not empty function to validate the req.body
- created an Authorization controller to validate the user token
#### How should this be manually tested?
** npm pull from the origin Branch from staging
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[Finishes #167729793] 
#### Screenshots (if appropriate)
![ReturnTrip](https://user-images.githubusercontent.com/43038045/64151761-eb43c900-cddf-11e9-98a0-ca61de0d17d0.JPG)

#### Questions:
N/A

2019-09-03 21:12 UTC, chibytez requested changes

2019-09-03 21:12 UTC, chibytez commented on src/controllers/returnTrip.js
> +                    message: 'Departure date and Return date cant be the same'
Can you please fix your can't

2019-09-03 21:12 UTC, chibytez commented on src/controllers/returnTrip.js
> +                user_id: id,
We are using camel case not snake case

2019-09-03 21:12 UTC, chibytez commented on src/controllers/returnTrip.js
> +                        user_id: id,
Deto

2019-09-03 21:12 UTC, chibytez commented on src/controllers/returnTrip.js
> +                        return_date: returnDateUTC,
deto

2019-09-03 21:12 UTC, chibytez commented on src/database/migrations/20190901024921-create-Trips.js
> +    user_id: {
Can we please change this to camel case

2019-09-03 21:12 UTC, chibytez commented on src/test/returntrip.test.js
> +            .end((err, res) => {
Can we also take care of the err

2019-09-05 13:01 UTC, chibytez requested changes
Can we add a screenshot to show that the test is passing

2019-09-05 13:14 UTC, chibytez requested changes

2019-09-05 13:14 UTC, chibytez commented on src/controllers/returnTrip.js
> +                    message: 'Departure and Return date can"t be the same'
can we fix it to can't

2019-09-05 13:14 UTC, chibytez commented on src/routes/api/index.js
> +usersRouter.use('/v1/trips', returntrip);
I think it should be /v1/users/trips

2019-09-05 13:14 UTC, chibytez commented on src/routes/api/returntrip.js
> +router.post('/request', Auth.authenticate, returntripvalidate.returnTrip, ValidationHandler.validate,  ReturnTrip.returnTripRequest );
I think your validation should be the first route

2019-09-05 13:14 UTC, chibytez commented on src/utils/ValidationHandler.js
> +            let results = Object.keys(mappedErrors).map(function (key) {
Can we use arrow function here

2019-09-05 13:14 UTC, chibytez commented on src/utils/helper/notEmpty.js
> +function notEmpty(value, msg) {
deto

2019-09-05 13:15 UTC, sebaztyn requested changes

2019-09-05 13:15 UTC, sebaztyn commented on src/models/Trip.js
> +        departureDate: {
Based on @Stylll 's recommendation, this should be a date type

2019-09-05 13:15 UTC, sebaztyn commented on src/models/Trip.js
> +        returnDate: {
This should have a date type too

2019-09-05 13:15 UTC, sebaztyn commented on src/models/Trip.js
> +        destination: {
This should be an array

2019-09-05 13:15 UTC, sebaztyn commented on src/routes/api/index.js
> +usersRouter.use('/v1/trips', returntrip);
All trip requests for oneway, return and multi-city should use just one route based on the advise of @Stylll

2019-09-05 13:15 UTC, sebaztyn commented on src/test/returntrip.test.js
> +                destination: 'Lagos',
Destination should be array of integers and current location should be an integer representing the current office location

2019-09-14 21:22 UTC, closed without merging