#167729797 User travel requests history
andela/shadowcat-backend pull request #32
Opened 2019-09-05 22:44 UTC by mthamayor

#### What does this PR do?
Users can get their travel requests history

#### Description of Task to be completed?
1. Create endpoint *GET api/v1/trips/request*
2. Document endpoint with swagger

#### How should this be manually tested?
After installing dependencies with `npm install`
- Run unit tests with `npm run tests`
- Start the server with `npm run dev`
- Sign up a user or log in an existing user to get user token
- From postman, create a get request *http://localhost:<your port | 3000>/api/v1/trips/request*, enter the `Bearer <token>` in the Authorization header
- You will receive a success response similar to the one in the image below
![Screenshot (190)](https://user-images.githubusercontent.com/16121915/64388061-c9438400-d035-11e9-8537-8a16d76822bd.png)

#### Any background context you want to provide?
- Please check the [implementation plan](https://docs.google.com/document/d/1ZTOHYHDVzirpfz1X15CWrym54MOwRKsXFeYoiC2f7ls/edit?usp=sharing) for `response` specifications
- There is a switch in Swagger versioning from swagger 2.0 to openapi 3.0.1 to enable access to use `Bearer <token>` for protected endpoints

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/167729797

#### Screenshots (if appropriate)
Proof of passing tests
![Screenshot (189)](https://user-images.githubusercontent.com/16121915/64387240-46212e80-d033-11e9-846f-9321be0f5774.png)

#### Questions:
None

2019-09-05 23:34 UTC, sebaztyn requested changes
Hey @mthamayor, I ran the endpoint on postman. It worked great for a user with an existing history.
When I signed up a new user and ran the request. Its return message was not clear as seen in the attached screenshot.
A message such as "No trip request found" or something in that form might be appropriate.
![image](https://user-images.githubusercontent.com/36090168/64390733-ee3bf500-d03d-11e9-8eae-a6cdd22e73ba.png)

2019-09-05 23:38 UTC, sebaztyn commented on src/test/getRequests.test.js
> +          const { status, data } = body;
I think you forgot to take down that console.log on line 124

2019-09-05 23:41 UTC, sebaztyn requested changes

2019-09-05 23:41 UTC, sebaztyn commented on src/test/getRequests.test.js
> +          console.log(data);
I think you forgot to take down that console.log on line 124

2019-09-06 00:24 UTC, sebaztyn approved these changes

2019-09-06 08:23 UTC, okabamac approved these changes

2019-09-06 09:09 UTC, Stylll requested changes
@mthamayor, Good work so far. Just a few comments. Please review.

2019-09-06 09:09 UTC, Stylll commented on .eslintrc.json
> +    "no-await-in-loop": "off",
This Eslint rule is turned off. It's a good practice not to use await inside a loop. You should turn this rule on.

2019-09-06 09:09 UTC, Stylll commented on src/controllers/userRequestHistory.js
> +import models from '../models';
Can we have this controller inside the Trips.js file instead? That file contains the methods to create trips so it'll be better if we have the method to get user trips in it also.

2019-09-06 12:57 UTC, Stylll requested changes
hey, @mthamayor I noticed there's no message in the response. Can we have a message saying something like this `Trips successfully retrieved` or `No trips available` if the user has no trips?.
@sebaztyn Pointed that out in his comments but it wasn't fixed.

2019-09-06 20:22 UTC, Stylll requested changes
Hey @mthamayor I noticed when one of the locations in a request destination array does not exist in the DB, (ie, in the requests table the destination column has two locations: 3, 989). 3 exists but 989 does not exist. This is the response that is returned

```
{
    "status": "error",
    "error": "a location does not exist"
}
```
Ideally, it should just return an empty object for that destination.

2019-09-10 09:11 UTC, sebaztyn approved these changes
I have tested locally and on postman. This get request works effectively.
Thank you.

2019-09-10 09:12 UTC, davidfrank96 approved these changes
Pulled it and it works fine on my machine

2019-09-10 10:57 UTC, Stylll approved these changes

2019-09-10 10:57 UTC, merged