#167729792-ft-one-way-trip-request
andela/shadowcat-backend pull request #37
Opened 2019-09-11 21:06 UTC by okabamac

#### What does this PR do?
This PR enables user to request a one-way trip

#### Description of Task to be completed?
- create controller to handle one-way
- create methods to switch request
- validate user inputs
- write test for controller
- ensure appropriate response items are returned

#### How should this be manually tested?
 - clone repository
- startup terminal
- cd into the cloned repository
- start the server by typing ```npm run dev``` into the terminal
- visit via postman and make a post request with 'one-way' in the request body to
 ```http://localhost:3000/api/v1/trips/requests```

#### Any background context you want to provide?
- User must be signed up and logged in
- User must a valid, unexpired token.

#### What are the relevant pivotal tracker stories?
[#167729792](https://www.pivotaltracker.com/story/show/167729792)

#### Screenshots (if appropriate)
![Screenshot from 2019-09-11 21-44-31](https://user-images.githubusercontent.com/30778719/64735212-03060600-d4e0-11e9-9458-4f89cf86d039.png)
![Screenshot from 2019-09-11 22-05-32](https://user-images.githubusercontent.com/30778719/64735369-511b0980-d4e0-11e9-8c5b-2d9933976b41.png)

#### Questions:
None

2019-09-12 08:33 UTC, sebaztyn requested changes

2019-09-12 08:33 UTC, sebaztyn commented on src/controllers/Trips.js
> +        return serverResponse(res, 400, ...['error', 'message', 'Line Manager must be present to continue']);
Hello @okabamac, kindly review the choice of return message. The message appears to require the line manager's physical presence

2019-09-12 08:59 UTC, okabamac commented on src/controllers/Trips.js
> +        return serverResponse(res, 400, ...['error', 'message', 'Line Manager must be present to continue']);
I think it's the same with yours. I just move Chidinma work

2019-09-12 09:03 UTC, davidfrank96 approved these changes
pls take note if the comment is not relevant u can ignore but I think this is okay

2019-09-12 09:03 UTC, davidfrank96 commented on src/controllers/Trips.js
>            returnDate,
Are u adding a returndate here?

2019-09-12 09:25 UTC, okabamac commented on src/controllers/Trips.js
>            returnDate,
Updated the GET Request to fetch the return date

2019-09-12 10:14 UTC, mthamayor requested changes
Hey mark. Nice work so far. However, I noticed in the request spec for multicity, the 'destination' property takes an array, while in `one-way` the  'destination` property takes an integer. I would suggest you follow the existing format of taking an array of integers. but in your case, only one value should be present in the array. Can you please look into it?

2019-09-12 10:19 UTC, okabamac commented
> Hey mark. Nice work so far. However, I noticed in the request spec for multicity, the 'destination' property takes an array, while in `one-way` the 'destination` property takes an integer. I would suggest you follow the existing format of taking an array of integers. but in your case, only one value should be present in the array. Can you please look into it?

I have implemented this feedback. Can you please confirm?

2019-09-12 10:23 UTC, mthamayor requested changes
Hello. After signing up and receiving a token. I put the token in the Authorization header as `Bearer <token>`  and made a request. Then i get
```
{
    "status": "error",
    "message": "Cannot Find User With Email: undefined"
}
```
Can you please look into this?

2019-09-12 10:25 UTC, mthamayor commented
> > Hey mark. Nice work so far. However, I noticed in the request spec for multicity, the 'destination' property takes an array, while in `one-way` the 'destination` property takes an integer. I would suggest you follow the existing format of taking an array of integers. but in your case, only one value should be present in the array. Can you please look into it?
> 
> I understand, but I don't think it is necessarily because I am still saving it as an array. And I was thinking it will be too much stress prompting the user to enter an array for a single value

This is why I asked the TTL about the format. I think it would do the team good if we have the same request for all the create trip requests endpoint

2019-09-12 10:42 UTC, okafor-chidimma approved these changes
tested locally and all tests are passing

2019-09-12 10:44 UTC, okabamac commented
> > > Hey mark. Nice work so far. However, I noticed in the request spec for multicity, the 'destination' property takes an array, while in `one-way` the 'destination` property takes an integer. I would suggest you follow the existing format of taking an array of integers. but in your case, only one value should be present in the array. Can you please look into it?
> > 
> > 
> > I understand, but I don't think it is necessarily because I am still saving it as an array. And I was thinking it will be too much stress prompting the user to enter an array for a single value
> 
> This is why I asked the TTL about the format. I think it would do the team good if we have the same request for all the create trip requests endpoint

OK. Let me get clarifications. Thanks alot

2019-09-12 15:27 UTC, okabamac commented
> Hello. After signing up and receiving a token. I put the token in the Authorization header as `Bearer <token>` and made a request. Then i get
> 
> ```
> {
>     "status": "error",
>     "message": "Cannot Find User With Email: undefined"
> }
> ```
> 
> Can you please look into this?

OK. It has been refactored by Chidinma and I sort of agree because only logged in user can make operations (user that has signed up and has verified his account). The token you get after signup doesnt attaches the email but when once you logged in that other token has email attached. Don't know if you're comfortable with it.

2019-09-12 19:06 UTC, okabamac commented
> > > Hey mark. Nice work so far. However, I noticed in the request spec for multicity, the 'destination' property takes an array, while in `one-way` the 'destination` property takes an integer. I would suggest you follow the existing format of taking an array of integers. but in your case, only one value should be present in the array. Can you please look into it?
> > 
> > 
> > I understand, but I don't think it is necessarily because I am still saving it as an array. And I was thinking it will be too much stress prompting the user to enter an array for a single value
> 
> This is why I asked the TTL about the format. I think it would do the team good if we have the same request for all the create trip requests endpoint

I just implemented the feedback. Thanks a lot

2019-09-13 03:31 UTC, sebaztyn approved these changes

2019-09-13 08:00 UTC, mthamayor approved these changes

2019-09-13 09:04 UTC, Stylll approved these changes

2019-09-13 09:05 UTC, merged